### ISSUE TITLE
Visual Studio 2017 support

### ISSUE THREAD

**Issue by wilhelmmedetz** [marcjohnston/byMarc.VS2015IX.RenameProjectFolder#1]
Could you add support for Visual Studio 2017?

**Comment by marcjohnston** [comment]
Support for Visual Studio 2017 is now available.  Find the product published here:
https://marketplace.visualstudio.com/vsgallery/01d4f846-f3f8-4d76-9444-602a1e26daa7

**Comment by marcjohnston** [comment]
Support for Visual Studio 2017 is now available.  Find the product published here:
https://marketplace.visualstudio.com/vsgallery/01d4f846-f3f8-4d76-9444-602a1e26daa7
--
